# Generated by Django 4.0.4 on 2022-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('crm', models.CharField(max_length=256)),
                ('especializacao', models.CharField(max_length=256)),
                ('turno', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('senha', models.CharField(max_length=256)),
            ],
        ),
    ]
