# Generated by Django 3.2.13 on 2022-06-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='agendarConsulta',
            new_name='turno',
        ),
    ]
