# Generated by Django 3.2.13 on 2022-06-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_agendarconsulta_agendamento_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarconsulta',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13),
        ),
    ]
