# Generated by Django 3.2.13 on 2022-06-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220621_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='agendarConsulta',
            new_name='Consulta',
        ),
    ]
