# Generated by Django 3.2.13 on 2022-06-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_rename_agendarconsulta_consulta_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='Consulta',
            new_name='tipo_Da_Consulta',
        ),
    ]
