# Generated by Django 3.2.13 on 2022-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_pessoa_agendamento_nome_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarconsulta',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='agendarconsulta',
            name='tipo_Da_Consulta',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='agendarconsulta',
            name='turno',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=256, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='turno',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='num_Do_Cartao_Do_Sus',
            field=models.CharField(max_length=19, unique=True, verbose_name='Número Do Cartão do SUS'),
        ),
    ]
