# Generated by Django 3.2.13 on 2022-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20220622_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarconsulta',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='agendarconsulta',
            name='turno',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='medico',
            name='turno',
            field=models.CharField(max_length=5),
        ),
    ]
