# Generated by Django 3.2.13 on 2022-06-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20220622_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome_De_Usuario',
        ),
    ]
