# Generated by Django 3.2.13 on 2022-06-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20220623_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='endereco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_De_Usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa'),
            preserve_default=False,
        ),
    ]
