# Generated by Django 3.2.13 on 2022-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20220623_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('SD', 'Segunda'), ('TC', 'Terça'), ('QR', 'Quarta'), ('QI', 'Quinta'), ('ST', 'Sexta')], default='SD', max_length=2, null=True),
        ),
    ]
