# Generated by Django 3.2.13 on 2022-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20220623_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
