# Generated by Django 3.2.13 on 2022-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_agendamento_dia_da_semana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='dia_da_semana',
            new_name='dia_Da_Semana',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_De_Agendamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
