# Generated by Django 3.2.13 on 2022-06-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20220628_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_De_Agendamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data De Agendamento'),
        ),
    ]
