# Generated by Django 3.2.13 on 2022-06-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_pessoa_username'),
        ('cadastros', '0013_alter_agendamento_data_de_agendamento'),
    ]

    operations = [
    ]
