# Generated by Django 3.2.13 on 2022-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_merge_20220629_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dia_Da_Semana',
            field=models.CharField(max_length=13),
        ),
    ]
