# Generated by Django 3.2.13 on 2022-06-23 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Completo', models.CharField(max_length=256, null=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('data_De_Nascimento', models.DateField(null=True)),
                ('num_Do_Cartao_Do_Sus', models.CharField(max_length=19, null=True, unique=True, verbose_name='Número Do Cartão do SUS')),
                ('telefone', models.CharField(max_length=15, null=True, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
