# Generated by Django 3.2.13 on 2022-06-23 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=2560, null=True, verbose_name='Endereço')),
                ('num_Da_Residencia', models.CharField(max_length=2, null=True, verbose_name='Número da Residência')),
                ('complemento', models.CharField(max_length=256, null=True)),
                ('bairro', models.CharField(max_length=256, null=True)),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='CEP')),
                ('ponto_De_Referencia', models.TextField(max_length=256, null=True, verbose_name='Ponto de Referência')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
