# Generated by Django 3.2.13 on 2022-06-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Do_Cartao_Do_SUS', models.CharField(max_length=256)),
                ('cPF', models.CharField(max_length=256)),
                ('data_De_Nascimento', models.DateField(null=True)),
                ('telefone', models.CharField(max_length=256)),
                ('rua', models.CharField(max_length=256)),
                ('cEP', models.CharField(max_length=256)),
                ('numero_Da_Residencia', models.CharField(max_length=256)),
                ('bairro', models.CharField(max_length=256)),
                ('complemento', models.CharField(max_length=256)),
                ('referencia', models.TextField(max_length=256)),
            ],
        ),
    ]
