# Generated by Django 4.0.4 on 2022-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao_sus', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=256)),
                ('nome_completo', models.CharField(max_length=256)),
                ('data', models.DateField(null=True)),
                ('telefone', models.CharField(max_length=256)),
            ],
        ),
    ]
