# Generated by Django 3.2.13 on 2022-06-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendarConsulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='rua',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='referencia',
            new_name='ponto_De_Referencia',
        ),
    ]
