# Generated by Django 4.0.4 on 2022-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
