# Generated by Django 3.2.13 on 2022-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_medico_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='nome_completo',
            new_name='nome_Completo',
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=256, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especializacao',
            field=models.CharField(max_length=256, verbose_name='Especialização'),
        ),
    ]
