# Generated by Django 3.2.13 on 2022-06-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListS', models.CharField(choices=[('SEG', 'Segunda'), ('TERC', 'Terça'), ('QUAR', 'Quarta'), (' QUIN', 'Quinta'), ('SEX', 'Sexta')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.CharField(choices=[('MN', 'Manhã'), ('TD', 'Tarde'), ('NT', 'Noite')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('tipo_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.tipoconsulta')),
            ],
        ),
    ]
