# Generated by Django 3.2.13 on 2022-06-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendar_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2, null=True),
        ),
    ]
