# Generated by Django 3.2.13 on 2022-06-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_auto_20220615_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendar',
            old_name='year_in_school',
            new_name='dia_da_semana',
        ),
    ]
