# Generated by Django 3.2.13 on 2022-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_rename_year_in_school_agendar_dia_da_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='turno',
            field=models.CharField(blank=True, choices=[('MH', 'Manhã'), ('TD', 'Tarde'), ('NT', 'Noite')], default='MH', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='agendar',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('SD', 'Segunda'), ('TC', 'Terça'), ('QR', 'Quarta'), ('QI', 'Quinta'), ('ST', 'Sexta')], default='SD', max_length=2, null=True),
        ),
    ]
