# Generated by Django 3.2.13 on 2022-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Da_Consulta', models.CharField(max_length=256)),
                ('turno', models.CharField(max_length=256)),
                ('dia_Da_Semana', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
